# .github/labeler.yml
---
# Add 'Multicast' label to any core file changes
Multicast:
  - changed-files:
    - any-glob-to-any-file:
      - multicast/*.py
      - LICENSE
      - LICENSE.md
      - Logo.svg
      - pyproject.toml

# Add 'Lint' label to any lint file changes
Linter:
  - changed-files:
    - any-glob-to-any-file:
      - '.ast-grep/**/*.yml'
      - .yamllint.conf
      - .bandit.yml
      - .flake8.ini
      - .coveragerc
      - .deepsource.toml
      - .markdownlint.yaml
      - tests/check_s*
      - tests/check_c*
      - tests/check_pip
      - '.github/actions/*/action.yml'
      - '.github/workflows/*'

# Add 'Bash Lang' label to any bash file changes
Bash Lang:
  - changed-files:
    - any-glob-to-any-file:
      - tests/*.bash
      - tests/check_*
      - .github/*.bash
      - .github/*.sh
      - .github/**/*.bash
      - .github/**/*.sh
      - .circleci/*.bash
      - '*.bash'

# Add 'Lang' label to any python file changes
Python Lang:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - '*.py'

# Add 'Make Lang' label to any Makefile file changes
Make Lang:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.makefile'
      - '**/*.make'
      - '**/makefile'
      - Makefile

# Add 'Configs' label to any configuration file changes
Configs:
  - changed-files:
    - any-glob-to-any-file:
      - '*.yml'
      - '*.yaml'
      - './**/*.yml'
      - './.**/*.yml'
      - '*.ini'
      - '*.toml'
      - '*.cfg'
      - '*.conf'
      - '.coveragerc'
      - '.gitattributes'
      - '.gitignore'
      - requirements.txt
      - tests/requirements.txt
      - docs/requirements.txt

# Add 'documentation' label to any documentation file changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - './**/*.md'
      - 'docs/**/*'
      - 'docs/*'
      - '.readthedocs.yaml'
      - generate_changelog.sh
      - README.md

# Add 'Testing' label to any testing file changes
Testing:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/*.py'
      - test-requirements.txt
      - tests/requirements.txt
      - 'tests/check_*'
      - '.github/tools/*.bash'
      - '.github/tools/*.sh'
      - '.github/tools/*.py'
      - '.github/workflows/*.yml'
      - '.circleci/*'

# Add 'CI' label to any CI/CD file changes
CI:
  - changed-files:
    - any-glob-to-any-file:
      - tests/*.py
      - tests/requirements.txt
      - .travis.yml
      - .appveyor.yml
      - '.circleci/*'
      - '.github/tool_*.sh'
      - '.github/tools/*'
      - '.github/actions/*/action.yml'
      - '.github/workflows/*'

# Add 'GitHub' label to any GitHub file changes
GitHub:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
      - .github/*
      - README.md
      - LICENSE.md
      - docs/SECURITY.md

# Add Special Case labels to any special-case file changes

invalid:
  - changed-files:
    - any-glob-to-any-file:
      - .stickler.yml
      - .hound.yml
      - setup.py
      - .markdownlint.yml
      - '.git_skipList'

JavaScript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.js'
      - 'package.json'
