linters:
  shellcheck:
    shell: bash
  flake8:
    max-line-length: 100
    max-complexity: 10
    ignore: 'W191,W391'
    exclude: ['.git', '__pycache__', 'docs', '.tox', 'build']
    format: default
files:
  ignore: ['*/*.pyc', '.tox/*', '*.pyc', '*~', '.git', '__pycache__', '*/__pycache__/*', '.git', 'tests']
