#! /bin/bash
# Disclaimer of Warranties.
# A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
#    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
#    BY OR ACCESSED THROUGH THIS SHELL SCRIPT IS AT YOUR SOLE RISK AND
#    THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
#    EFFORT IS WITH YOU.
#
# B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
#    AND SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND
#    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT'S LICENSORS
#    (COLLECTIVELY REFERRED TO AS "THE AUTHOR" FOR THE PURPOSES OF THIS DISCLAIMER)
#    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
#    SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
#    NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF
#    MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
#    ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.
#
# C. THE AUTHOR DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE
#    THE AUTHOR's SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN, OR
#    SERVICES PERFORMED OR PROVIDED BY, THIS SHELL SCRIPT WILL MEET YOUR
#    REQUIREMENTS, THAT THE OPERATION OF THIS SHELL SCRIPT OR SERVICES WILL
#    BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICES WILL CONTINUE TO BE MADE
#    AVAILABLE, THAT THIS SHELL SCRIPT OR SERVICES WILL BE COMPATIBLE OR
#    WORK WITH ANY THIRD PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES,
#    OR THAT DEFECTS IN THIS SHELL SCRIPT OR SERVICES WILL BE CORRECTED.
#    INSTALLATION OF THIS THE AUTHOR SOFTWARE MAY AFFECT THE USABILITY OF THIRD
#    PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES.
#
# D. YOU FURTHER ACKNOWLEDGE THAT THIS SHELL SCRIPT AND SERVICES ARE NOT
#    INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE
#    OR TIME DELAYS OF, OR ERRORS OR INACCURACIES IN, THE CONTENT, DATA OR
#    INFORMATION PROVIDED BY THIS SHELL SCRIPT OR SERVICES COULD LEAD TO
#    DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE,
#    INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
#    NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR
#    WEAPONS SYSTEMS.
#
# E. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY THE AUTHOR
#    SHALL CREATE A WARRANTY. SHOULD THIS SHELL SCRIPT OR SERVICES PROVE DEFECTIVE,
#    YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#    Limitation of Liability.
# F. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHOR
#    BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR
#    CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES
#    FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR
#    RECEIVE ANY DATA OR INFORMATION, BUSINESS INTERRUPTION OR ANY OTHER
#    COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR
#    INABILITY TO USE THIS SHELL SCRIPT OR SERVICES OR ANY THIRD PARTY
#    SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH THIS SHELL SCRIPT OR
#    SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
#    TORT OR OTHERWISE) AND EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION
#    OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR
#    CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event
#    shall THE AUTHOR's total liability to you for all damages (other than as may
#    be required by applicable law in cases involving personal injury) exceed
#    the amount of five dollars ($5.00). The foregoing limitations will apply
#    even if the above stated remedy fails of its essential purpose.
################################################################################

ulimit -t 60
# setting the path may break brain-dead CI that uses crazy paths
# PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
umask 137

# exported Env vars
# shellcheck disable=SC2155
export LC_CTYPE="${LC_CTYPE:-'en_US.UTF-8'}"

# Function to check if a command exists.

# USAGE:
#  ~$ check_command CMD
# Arguments:
# CMD (Required) -- Name of the command to check
# Results:
#    exits 64 -- missing required argument
#    exits 126 -- check complete and has failed, can not find given command.
#    returns successful -- check complete and command found to be executable.
function check_command() {
    test -z "$1" && { printf "%s\n" "Error: command name is required to check for existence." >&2 ; exit 64 ; } ;
    local cmd="$1" ;
    # shellcheck disable=SC2086
    test -x "$(command -v ${cmd})" || { printf "%s\n" "Error: Required command '$cmd' is not found." >&2 ; exit 126 ; } ;
}  # end check_command()
# propagate/export function to sub-shells
export -f check_command

# Set up CEP-5 shlock helper
hash -p ./.github/tool_shlock_helper.sh shlock || { printf "%s\n" "Error: Failed to register shlock helper. CEP-5 locking will not work." >&2 ; exit 78 ; } ;

# Check required commands
check_command grep ;
check_command python3 ;
check_command make ;
check_command git ;
check_command tee ;
check_command shlock ;

# rest of the script vars
LOG_FILE="test_log_${PPID}.log"
ERR_FILE="test_log_errors_${PPID}.log"
LOCK_FILE="${TMPDIR:-/tmp}/org.pak.multicast.cov-integration-shell"
EXIT_CODE=1

function cleanup() {
	rm -f ./"${LOG_FILE}" 2>/dev/null || true ; wait ;
	rm -f ./"${ERR_FILE}" 2>/dev/null || true ; wait ;
	rm -f "${LOCK_FILE}" 2>/dev/null || true ; wait ;
	hash -d shlock 2>/dev/null > /dev/null || true ;
}

if [[ ( $(shlock -f "${LOCK_FILE}" -p $$ ) -eq 0 ) ]] ; then
		EXIT_CODE=0
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
		# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
		# shellcheck disable=SC2173
		#trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE} 2>/dev/null > /dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
		# shellcheck disable=SC2086
		trap 'cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
else
		# shellcheck disable=SC2046
		printf "%s\n" "Check Integration Tests Coverage already in progress by "$(head "${LOCK_FILE}") >&2 ;
		exit 126 ;
fi

# setup test fixtures

# this is how test files are found:
if _TEST_ROOT_DIR=$(git rev-parse --show-superproject-working-tree 2>/dev/null); then
	if [ -z "${_TEST_ROOT_DIR}" ]; then
		_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
	fi
else
	printf "\t%s\n" "FAIL: missing valid repository or source structure" >&2
	EXIT_CODE=40
fi

TEST_MCAST_PORT=$(((RANDOM % 16384) + 49152));
TEST_MCAST_GROUP='224.0.0.1' ;
COVERAGE_DATA_FILE="./coverage_integration" ;
if [[ -x "${PYTHON}" ]] ; then
	PY_3_CMD="${PYTHON}"
else
	PY_3_CMD=$(command -v python3);
fi ;
printf "%s\n" "::debug:: Will Use ${PY_3_CMD}"
# shellcheck disable=SC2086
COVERAGE_CMD="${PY_3_CMD} -m coverage run -p --source=multicast -m";
export COVERAGE_CMD

# start test-suite

make -j1 -f Makefile test-reports || EXIT_CODE=3 ;
printf "%s\n\n" "Start of Log:" > ./"${LOG_FILE}" ; wait ;
printf "%s\n\n" "Will use host-port: [${TEST_MCAST_GROUP} : ${TEST_MCAST_PORT}]" >> ./"${LOG_FILE}" ; wait ;
printf "%s\n\n" "Start of Integration Test one-shot:" >> ./"${LOG_FILE}" ; wait ;
# shellcheck disable=SC2086
( sleep 1 ; ${COVERAGE_CMD} multicast --use-std RECV --port "${TEST_MCAST_PORT}" --groups "${TEST_MCAST_GROUP}" --group "${TEST_MCAST_GROUP}" 2>./"${ERR_FILE}" & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./"${LOG_FILE}" & true ;

for PCOUNT in $(seq 1 5) ; do
	# Test message sending operations rapidly
	# shellcheck disable=SC2086
	${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "TEST from ${PCOUNT}" 2>/dev/null & : ;
done ;
# shellcheck disable=SC2086
${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "STOP from $TEST_MCAST_GROUP" 2>/dev/null & sleep 1 ;
# shellcheck disable=SC2086
${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "STOP" 2>/dev/null ;
printf "%s\n\n" "End of Integration Test one-shot" >> ./"${LOG_FILE}" ; wait ;

printf "%s\n\n" "Start of Integration Test daemon:" >> ./"${LOG_FILE}" ; wait ;
# shellcheck disable=SC2086
( sleep 1 ; ${COVERAGE_CMD} multicast --daemon HEAR --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" 2>./"${ERR_FILE}" & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./"${LOG_FILE}" & true ;

for PCOUNT in $(seq 1 5) ; do
	# Test concurrent message sending operations, all to the same destination group
	# shellcheck disable=SC2086
	${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "TEST from $PCOUNT" 2>/dev/null & : ;
done ;
# shellcheck disable=SC2086
${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "STOP from $TEST_MCAST_GROUP" 2>/dev/null & sleep 1 ;
# shellcheck disable=SC2086
${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "STOP" 2>/dev/null ;
wait ;
printf "%s\n\n" "End of Integration Test daemon" >> ./"${LOG_FILE}" ; wait ;

# test --pipe mode added in v2.1.0
printf "%s\n\n" "Start of Integration Test pipe:" >> ./"${LOG_FILE}" ; wait ;
# shellcheck disable=SC2086
( sleep 1 ; ${COVERAGE_CMD} multicast --daemon HEAR --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" 2>./"${ERR_FILE}" & sleep 6 ; kill -9 $! 2>/dev/null ) >> ./"${LOG_FILE}" & true ;

for NOISE_ID in $(seq 1 5) ; do
	# Test concurrent message sending operations, each using piped input
	# shellcheck disable=SC2086
	{ printf "%s\n" "TEST input from $NOISE_ID" | ${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --pipe 2>/dev/null ;} & : ;
done ;
# shellcheck disable=SC2086
printf "%s\n" "TEST input from $NOISE_ID" | ${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --pipe 2>/dev/null & sleep 1 ;
# shellcheck disable=SC2086
${COVERAGE_CMD} multicast SAY --port "${TEST_MCAST_PORT}" --group "${TEST_MCAST_GROUP}" --message "STOP" 2>/dev/null ;
wait ;
printf "%s\n\n" "End of Integration Test pipe" >> ./"${LOG_FILE}" ; wait ;

# cleanup from test-suite

# shellcheck disable=SC2086
${PY_3_CMD} -m coverage combine --data-file="${COVERAGE_DATA_FILE}" ./.coverage.* || EXIT_CODE=2 ;
if [[ -r "${COVERAGE_DATA_FILE}" ]] ; then
	# shellcheck disable=SC2086
	${PY_3_CMD} -m coverage report -m --include=multicast/* --data-file="${COVERAGE_DATA_FILE}" 2>/dev/null || EXIT_CODE=2 ;
	# shellcheck disable=SC2086
	${PY_3_CMD} -m coverage xml -o ./test-reports/coverage_supplement.xml --include=multicast/* --data-file="${COVERAGE_DATA_FILE}" || EXIT_CODE=2 ;
else
	printf "%s\n" "::error file='${0}',title='No Coverage':: Coverage collection FAILED!" >>./"${ERR_FILE}" || EXIT_CODE=2 ;
fi ;
wait ;
cp -f ./"${LOG_FILE}" ./test-reports/integration_data_log.log 2>/dev/null ; wait ;
printf "%s\n" "" | tee -a ./test-reports/integration_data_log.log ; wait ;

if [[ ( -r ./${ERR_FILE} ) ]] ; then
	printf "%s\n" "Errors: " | tee -a ./test-reports/integration_data_log.log ; wait ;
	cat <./"${ERR_FILE}" | tee -a ./test-reports/integration_data_log.log ; wait ;
fi

unset COVERAGE_CMD 2>/dev/null || : ;
unset TEST_MCAST_GROUP 2>/dev/null || : ;
unset TEST_MCAST_PORT 2>/dev/null || : ;

cleanup || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || true ; wait ;

# shellcheck disable=SC2086
exit ${EXIT_CODE:-255} ;
